import Vue from 'vue'
import { Icon, Toast, NavBar, Tabbar, TabbarItem, Search, Swipe, SwipeItem, Grid, GridItem, ActionSheet, Rate, Dialog, Checkbox, CheckboxGroup, Tab, Tabs } from 'vant'

Vue.use(Tab)
Vue.use(Tabs)
Vue.use(Checkbox)
Vue.use(CheckboxGroup)
Vue.use(Dialog)
Vue.use(Rate)
Vue.use(ActionSheet)
Vue.use(Icon)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Search)
Vue.use(Toast)
Vue.use(NavBar)
Vue.use(Tabbar)
Vue.use(TabbarItem)
